### ISSUE TITLE
'replace' of undefined

### ISSUE THREAD

**Issue by idoo** [daniel-nagy/md-data-table#159]
Can somebody help me, how i can fix this error?
```
TypeError: Cannot read property 'replace' of undefined
    at Object.directiveNormalize [as $normalize] (http://local.dev:5000/assets/angular/angular-56b1d9851d943a97f0ceddd96df3c18e.js?body=1:8906:24)
    at Object.a [as compile] (http://local.dev:5000/assets/angular-material-data-table/md-data-table.min-bd5fbbe4def152c511c11197281f1c8c.js?body=1:1:1739)
    at applyDirectivesToNode (http://local.dev:5000/assets/angular/angular-56b1d9851d943a97f0ceddd96df3c18e.js?body=1:8070:32)
    at compileNodes (http://local.dev:5000/assets/angular/angular-56b1d9851d943a97f0ceddd96df3c18e.js?body=1:7599:15)
    at compileNodes (http://local.dev:5000/assets/angular/angular-56b1d9851d943a97f0ceddd96df3c18e.js?body=1:7611:15)
    at compileNodes (http://local.dev:5000/assets/angular/angular-56b1d9851d943a97f0ceddd96df3c18e.js?body=1:7611:15)
    at compileNodes (http://local.dev:5000/assets/angular/angular-56b1d9851d943a97f0ceddd96df3c18e.js?body=1:7611:15)
    at compile (http://local.dev:5000/assets/angular/angular-56b1d9851d943a97f0ceddd96df3c18e.js?body=1:7506:15)
    at http://local.dev:5000/assets/angular-ui-router/angular-ui-router-bad4adca9e83c760b84478b4986498b2.js?body=1:4014:20
    at invokeLinkFn (http://local.dev:5000/assets/angular/angular-56b1d9851d943a97f0ceddd96df3c18e.js?body=1:8790:9) <table class="md-primary" md-data-table="">
```

**Comment by richshaw** [comment]
I'm getting the same error. I haven't figure out what's causing it yet. For me, the error occurs when using the minified version of md-data-table (md-data-table.min.js) on a table that doesn't contain ng-repeat. 

Example on Codepen: http://codepen.io/anon/pen/NGwMvR

Not a fix, but you can avoid the error by using the regular md-data-table.js or adding ng-repeat to your table.

**Comment by jsmylnycky** [comment]
One of our team devs suggested this can occur when the table is hidden as well.

In our setup, we're using mdTabs with mdDataTable on the second tab and third tab, which wouldn't be visible on page load.  Due to this, we immediately get the error twice.

**Comment by hoopyfrood** [comment]
+1, using it in combination with md-tabs too, suspect it has to do with being hidden much like @jsmylnycky's description

**Comment by rudzikdawid** [comment]
```
TypeError: Cannot read property 'length' of undefined
    at Object.getAttr (http://localhost:3000/bower_components/angular-material-data-table/dist/md-data-table.js:645:29)
    at Object.compile (http://localhost:3000/bower_components/angular-material-data-table/dist/md-data-table.js:130:29)
    at applyDirectivesToNode (http://localhost:3000/bower_components/angular/angular.js:8069:32)
    at compileNodes (http://localhost:3000/bower_components/angular/angular.js:7598:15)
    at compileNodes (http://localhost:3000/bower_components/angular/angular.js:7610:15)
    at http://localhost:3000/bower_components/angular/angular.js:8490:38
    at processQueue (http://localhost:3000/bower_components/angular/angular.js:14745:28)
    at http://localhost:3000/bower_components/angular/angular.js:14761:27
    at Scope.$eval (http://localhost:3000/bower_components/angular/angular.js:15989:28)
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:15800:31) <table md-data-table="" class="md-primary" md-row-select="selected" md-progress="deferred">
```

+1

**Comment by bartlx** [comment]
Same, +1

**Comment by mpnowacki** [comment]
+1

**Comment by majkelch** [comment]
+1

**Comment by wizjack** [comment]
Yup for me it's for ng-repeat, without it the error is thrown.

**Comment by intraflank** [comment]
I'm having the same issue as wizjack, +1.

**Comment by rfuhrer** [comment]
I was having the same issue with some tables that were inside an md-tab

The problem seems to be caused by this line:
`console.log(b.$normalize(e.attr("ng-repeat"))),`
This seems like some sort of test line that somehow lived way too long.  Why would you be writing to the console while building the table?  I simply went into the JS file, removed this line and now everything works great and no errors are displayed in my console.  That exact string only shows up once in the whole JS file so do a simple find and replace with blank and you should be good.

**Comment by nicolac18** [comment]
+1

**Comment by petarsubotic** [comment]
+1 when using .min without ng-repeat on data rows.

Also,
`data-ng-repeat` was also behaving odd so i replaced it with a regular `ng-repeat` which worked well
https://github.com/daniel-nagy/md-data-table/blob/master/app/templates/nutrition-table.html#L26

**Comment by rudzikdawid** [comment]
Isuue was solved in 0.9.X

:+1:
