### ISSUE TITLE
Generic Error

### ISSUE THREAD

**Issue by vapits** [daniel-nagy/md-data-table#191]
Hey,

i tried to use md-data-table to my angular project but it seems there is an error.
Is use Angular 1.3.15, install with bower install and use of browserify.

The error i'm getting is very generic:
````bash
Error: mdDataTable
    at Object.a [as compile] (http://localhost:8001/src/js/libsBundle.js:4596:1388)
    at applyDirectivesToNode (http://localhost:8001/src/js/libsBundle.js:74624:32)
    at compileNodes (http://localhost:8001/src/js/libsBundle.js:74165:15)
    at compileNodes (http://localhost:8001/src/js/libsBundle.js:74177:15)
    at compileNodes (http://localhost:8001/src/js/libsBundle.js:74177:15)
    at compile (http://localhost:8001/src/js/libsBundle.js:74072:15)
    at link (http://localhost:8001/src/js/libsBundle.js:89639:9)
    at invokeLinkFn (http://localhost:8001/src/js/libsBundle.js:75384:9)
    at nodeLinkFn (http://localhost:8001/src/js/libsBundle.js:74894:11)
    at compositeLinkFn (http://localhost:8001/src/js/libsBundle.js:74243:13) <table md-data-table="">
````

My code html is simple enough:
````html
    <md-data-table-container>
        <table md-data-table>
            <tbody>
                <tr ng-repeat="item in datasetData.data">
                    <td>{{item}}</td>
                </tr>
            </tbody>
        </table>
    </md-data-table-container>
````

Any ideas?

**Comment by truginis** [comment]
Try adding <thead><tr><th> to your table. I get errors if I don't add it.



Sent via the Galaxy S®6


-------- Original message --------

**Comment by vapits** [comment]
Did that nothing changed.

**Comment by vapits** [comment]
Nuh now it's working, not changed anything. maybe a cache (?) issue. sorry.
